export default {
  SET_COOKIE: 'SET_COOKIE',
  REMOVE_COOKIE: 'REMOVE_COOKIE',

  SET_TODO: 'SET_TODO',
  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',

  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  SET_USER_TOKEN: 'SET_USER_TOKEN',
  SET_USER_DATA: 'SET_USER_DATA',

  UPDATE_LOCALE: 'UPDATE_LOCALE',
};
