export default {
  UNKNOWN_EXCEPTION: 'UNKNOWN_EXCEPTION',
  ODM_OPERATION_FAIL: 'ODM_OPERATION_FAIL',
  STATE_PRE_FETCHING_FAIL: 'STATE_PRE_FETCHING_FAIL',
  USER_UNAUTHORIZED: 'USER_UNAUTHORIZED',
  USER_EXISTED: 'USER_EXISTED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  LOCALE_NOT_SUPPORTED: 'LOCALE_NOT_SUPPORTED',
  USER_TOKEN_EXPIRATION: 'USER_TOKEN_EXPIRATION',
  ODM_VALIDATION: 'ODM_VALIDATION',
  INVALID_RECAPTCHA: 'INVALID_RECAPTCHA',
  SOCIAL_AUTH_FAIL: 'SOCIAL_AUTH_FAIL',
  SEND_EMAIL_FAIL: 'SEND_EMAIL_FAIL',
};
