export default {
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGIN: 'USER_LOGIN',
  USER_EDIT: 'USER_EDIT',
  USER_AVATAR: 'USER_AVATAR',
  USER_CHANGE_PASSWORD: 'USER_CHANGE_PASSWORD',
  USER_FORGET_PASSWORD: 'USER_FORGET_PASSWORD',
  USER_RESET_PASSWORD: 'USER_RESET_PASSWORD',
};
